# Etapa 1: Build do projeto Maven/Spring Boot
# Use uma imagem base do Maven
FROM maven:3.8.5-openjdk-17 AS build

# Defina o diretório de trabalho
WORKDIR /app

# Copie os arquivos de configuração do Maven e o código-fonte
COPY pom.xml .
COPY src ./src

# Construa o projeto, pulando os testes para agilizar o build
RUN mvn clean package -DskipTests

# Etapa 2: Rodar a aplicação
# Use uma imagem leve do OpenJDK
FROM openjdk:17-jdk-slim

# Defina o diretório de trabalho
WORKDIR /app

# Copie o arquivo .jar da etapa de build
COPY --from=build /app/target/*.jar app.jar

# Exponha a porta da aplicação Spring Boot
EXPOSE 8080

# Comando para rodar a aplicação
ENTRYPOINT ["java", "-jar", "app.jar"]